"""add transaction audit table

Revision ID: 713c59101334
Revises: f19d13cdb700
Create Date: 2026-08-26 18:11:46.718507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713c59101334'
down_revision = 'f19d13cdb700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('CREATED','UPDATED','DELETED','RESTORED')", name='ck_audit_action'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_audit', schema=None) as batch_op:
        batch_op.create_index('ix_audit_txn_time', ['transaction_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_audit_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_audit_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_audit_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_audit_transaction_id'))
        batch_op.drop_index('ix_audit_txn_time')

    op.drop_table('transaction_audit')
    # ### end Alembic commands ###
