"""add allow_overpayment preference

Revision ID: 75d634ee202b
Revises: 713c59101334
Create Date: 2026-08-26 18:13:35.469483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d634ee202b'
down_revision = '713c59101334'
branch_labels = None
depends_on = None


def upgrade():
    # Hand-edited after autogenerate, and this is the reason to always read a
    # generated migration before running it.
    #
    # Alembic wrote `nullable=False` with no default. That is correct for a new
    # table, but this one already has rows - and there is no value to put in the
    # new column for them, so the database refuses the change.
    #
    # server_default fills the existing rows with false. It stays on the column
    # afterwards, which is harmless: the model's own default=False governs every
    # insert the app makes, and the database default only ever applies to rows
    # written by something else.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'allow_overpayment',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allow_overpayment')

    # ### end Alembic commands ###
