"""initial schema

Revision ID: f19d13cdb700
Revises: 
Create Date: 2026-08-26 17:53:48.744713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19d13cdb700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_people_name_not_blank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_people_user_name', ['user_id', 'name'], unique=False)
        batch_op.create_index('uq_people_user_phone', ['user_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'), sqlite_where=sa.text('phone IS NOT NULL'))

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("due_date IS NULL OR type = 'LOAN'", name='ck_txn_due_date_loan_only'),
    sa.CheckConstraint("payment_method IS NULL OR payment_method IN ('CASH','BANK_TRANSFER','EWALLET','OTHER')", name='ck_txn_payment_method'),
    sa.CheckConstraint("type IN ('LOAN','PAYMENT')", name='ck_txn_type'),
    sa.CheckConstraint('amount > 0', name='ck_txn_amount_positive'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_txn_person_date', ['person_id', 'occurred_on', 'id'], unique=False)
        batch_op.create_index('ix_txn_user_date', ['user_id', 'occurred_on'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_date')
        batch_op.drop_index('ix_txn_person_date')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_person_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index('uq_people_user_phone', postgresql_where=sa.text('phone IS NOT NULL'), sqlite_where=sa.text('phone IS NOT NULL'))
        batch_op.drop_index('ix_people_user_name')
        batch_op.drop_index(batch_op.f('ix_people_user_id'))

    op.drop_table('people')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
